name: REST API CI
on:
  push:
    branches:
      - main
jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./rest
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todos
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: create table
        run: psql postgres://postgres:password@localhost:5432/todos -c "CREATE TABLE todos (id SERIAL PRIMARY KEY, title TEXT NOT NULL, finished BOOLEAN DEFAULT FALSE, description TEXT);"
      - name: install psql
        run: sudo apt-get install -y postgresql-client
      - name: use go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
      - name: run tests
        run: go test ./...
      - name: docker build
        run: docker build -t rest_api .